# Generated by Django 4.2.3 on 2023-07-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='click_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
