# Generated by Django 4.2.3 on 2023-07-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_click_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
